### ISSUE TITLE
Use `coincident` if `crossOriginIsolated`, `comlink` otherwise

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus#102]
Similar to https://github.com/jupyterlite/pyodide-kernel/pull/126

`jupyterlite-xeus` should use `coincident` if `crossOriginIsolated`, `comlink` otherwise, to fix the issue noticed in https://github.com/jupyterlite/jupyterlite/issues/1424.

As a follow-up to https://github.com/jupyterlite/xeus/pull/87

**Comment by jtpio** [comment]
Of note, `coincident` v2 was just released: https://github.com/WebReflection/coincident/releases/tag/v2.0.0

One of the changes is:

> the "maybe available" SharedArrayBuffer issue has been fully solved via [sabayon](https://github.com/WebReflection/sabayon#readme) which guarantee functionality with or without special headers enabled and it allows people to provide their Service Worker as long as they [add sabayon features](https://github.com/WebReflection/sabayon?tab=readme-ov-file#service-worker)

So maybe updating to the new version will remove the need for `comlink` (to be confirmed).

**Comment by martinRenou** [comment]
> it allows people to provide their Service Worker

This is a red flag for me though. Regular postMessage (what comlink does) should be enough.
