### ISSUE TITLE
xhr is called synchronously

### ISSUE THREAD

**Issue by trungleduc** [jupyterlite/xeus#106]
## Description

`getJson` helper is using `XMLHttpRequest` synchronously, which is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest_API/Synchronous_and_Asynchronous_Requests#synchronous_request) and does not work well with service worker. Is there any technical season to avoid async call here or can we convert this function to use `fetch`?

https://github.com/jupyterlite/xeus/blob/6504866ceb6b89000f3786f59dcb2e343bfb88c0/src/index.ts#L15-L20

**Comment by DerThorsten** [comment]
@trungleduc so if you can make [this part async](https://github.com/jupyterlite/xeus/blob/6504866ceb6b89000f3786f59dcb2e343bfb88c0/src/index.ts#L32-L87) then we of course can just use fetch

**Comment by trungleduc** [comment]
Thanks @DerThorsten, i will open a PR to fix this issue.
