### ISSUE TITLE
Release notes for 2.0.0

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus#118]
Currently the GitHub releases says "No merged PRs": https://github.com/jupyterlite/xeus/releases/tag/v2.0.0

![image](https://github.com/user-attachments/assets/af63f66d-b9d2-41cc-aca2-8e822d6fe83e)

It would be nice to list of changes that happened between 1.x and 2.0, for users not necessarily looking at the pre-releases.

**Comment by martinRenou** [comment]
Ah yeah I haven't seen this option. I actually auto-generated the changelog with Github right when you opened the issue.
