### ISSUE TITLE
xeus-python: Python 3.12 is showing up in the launcher, not Python 3.11

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/xeus#27]
## Description

Not technically related to jupyterlite-xeus, but I think we should fix it before releasing the 0.1.0 and replacing jupyterlite-xeus-python, hence opening it here.

This may require a fix in xeus-python, or an ugly patch of the kernel spec in emscripten-forge/recipes

**Comment by DerThorsten** [comment]
fixed via https://github.com/jupyter-xeus/xeus-python/pull/609, needs to be merged and released
