### ISSUE TITLE
xeus python does not load logo.

### ISSUE THREAD

**Issue by DerThorsten** [jupyterlite/xeus#43]
## Description

a pip installed jupyterlite-xeus does not yield a xeus-python with a proper logo.
Xeus python is installed  with micromamba and and xeus-lite is build with the `prefix` option.
This is very likely related to #36 

Console says:
`logo-svg.svg:1   Failed to load resource: the server responded with a status of 404 (File not found)`

**Comment by martinRenou** [comment]
Fix with the latest patch release
