### ISSUE TITLE
empack_config file filter does not seem to be working

### ISSUE THREAD

**Issue by katotetsuro** [jupyterlite/xeus#52]
## Description

The file filter specified in XeusAddon.empack_config is not used.

https://github.com/jupyterlite/xeus/blob/main/jupyterlite_xeus/add_on.py#L263-L287

## Reproduce

```
jupyter lite build --XeusAddon.empack_config=empack_config.yml
```

## Context

It might be better handled as follows

https://github.com/jupyterlite/xeus-python-kernel/blob/main/jupyterlite_xeus_python/build.py#L321

```
pack_env(
      env_prefix=self.prefix,
      relocate_prefix="/",
      outdir=out_path,
      use_cache=True,
      **pack_kwargs,
)
```

**Comment by martinRenou** [comment]
Thank you for opening an issue. I blame myself for not testing the feature properly. 


Would you like to open a PR to get credits for your fix?

**Comment by katotetsuro** [comment]
I would like to!
I have created a PR here.
https://github.com/jupyterlite/xeus/pull/53
