### ISSUE TITLE
Support for package data

### ISSUE THREAD

**Issue by nthiery** [jupyterlite/xeus#66]
## Description

I have a Python package which includes package data, to be accessed
through `importlib.resources`. However, within jupyterlite, `importlib.resources`
fails do find the data.

## Reproduce

1. Clone https://github.com/jupyterlite/xeus-python-demo
2.  Add these dependencies to environment.yml
    ```
      - pip
      - pip:
        - "git+https://gitlab.dsi.universite-paris-saclay.fr/nicolas.thiery/Laby.git"
    ```
3. Build JupyterLite
    ```
    mamba env create --force -f build-environment.yml
    conda activate build-env
    cp README.md content
    jupyter lite build --contents content --output-dir dist
    ```

4. Check the log, and notice the copying of the package data when building the wheel:
    ```
    creating build/bdist.linux-x86_64/wheel/laby/resources/tiles_png
    copying build/lib/laby/resources/tiles_png/nweb.png -> build/bdist.linux-x86_64/wheel/laby/resources/tiles_png
    ...
    ```
5. Browse `dist/extensions/@jupyterlite/xeus-python-kernel/static/laby_python-0.0.5-pip.tar.gz`

    **Expected behavior:** the archive contain the package data.
    **Got:** the package contains only the Python code

6.  Run JupyterLite and from a python kernel run:
     ```
     tiles_dir = importlib.resources.files("laby").joinpath("resources", "tiles_png")
     list(tiles_dir.glob("*"))
     ```
     **Expected behavior**:  a list of files including 'nweb.png`.  
     **Got**: the empty list

## Context

- JupyterLite version: 0.1.2
- Operating System and version: Ubuntu 22.04
- Browser and version: Firefox/chromium

**Comment by nthiery** [comment]
Hello! Bumping this issue, as this is a blocker for making our «Introduction to programming Python course» available outside of Paris-Saclay using JupyterLite.

Is this a hard problem? Do we have some estimate of when this could be fixed?

Thank you in advance!

**Comment by martinRenou** [comment]
> or at least completely drop the empack filtering...

Yeah 👍🏽 

I'd be curious to see what impact removing filtering would have, but it would definitely make the situation better.

**Comment by martinRenou** [comment]
I think I commented this somewhere, but I believe the filtering logic should be an opt-in and not an opt-out. We should not filter any file unless explicitly stated.

**Comment by martinRenou** [comment]
I can have a look at this

**Comment by nthiery** [comment]
Thank you @DerThorsten and @martinRenou for the quick feedback! Happy to beta test anytime.

**Comment by nthiery** [comment]
I confirm that this works with #96 on my use case. Closing ticket. Thank you!!!
