### ISSUE TITLE
No file system access

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus#75]
## Description

Trying the demo from https://github.com/jupyterlite/xeus-python-demo, it looks like file system operations are not supported with the service worker giving a 405 response:

![image](https://github.com/jupyterlite/xeus/assets/591645/346f1b28-1ad1-4bad-ad64-c158fc3255e0)

## Reproduce

Open https://jupyterlite.github.io/xeus-python-demo/ and try with:

```py
import os
os.listdir()
```

## Expected behavior

This should return the list of files.

## Context

- JupyterLite version: 0.2.3
- Operating System and version: Ubuntu 23.10
- Browser and version: Chromium 121

**Comment by jtpio** [comment]
For reference this was also noticed with https://github.com/jupyterlite/jupyterlite/pull/1316 and `jupyterlite-xeus==0.1.8` installed locally.

**Comment by jtpio** [comment]
Investigating this a bit more, this seems to be working fine with a regular (non-private) Firefox 122 tab:

![image](https://github.com/jupyterlite/xeus/assets/591645/d0fa391d-e67c-42bf-b845-0a60bc5bb602)


So not sure if it's just a local setup / browser issue, or if it's affecting other people too.

**Comment by DerThorsten** [comment]
for me it works in firefox and in a private chrome window, but in a non-chrome windows nothing works...kernel is idle but any operation is busy forever. Not sure if this is a caching issue.

**Comment by jtpio** [comment]
Unchecking "Bypass for network" in the dev tools seems to be helping (still in a private window):

![image](https://github.com/jupyterlite/xeus/assets/591645/1c0aa7d9-60e0-4ecc-927d-e25f5e91ea30)

Not sure if I had this option checked before or not.

**Comment by jtpio** [comment]
> Not sure if this is a caching issue.

It might be yes. Hopefully https://github.com/jupyterlite/jupyterlite/pull/1316 will help mitigate this.

Closing in favor of https://github.com/jupyterlite/jupyterlite/issues/1321 as something to be addressed in the JupyterLite repo.
