### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by DerThorsten** [jupyterlite/xeus#8]
A lot of the documentation can be copy pasted from https://github.com/jupyterlite/xeus-python-kernel, yet we need a bit more, since this repo has more capabilities.

**Comment by DerThorsten** [comment]
#16

**Comment by jtpio** [comment]
Shouldn't this issue be more about having a nice documentation on ReadTheDocs, like https://xeus-python-kernel.readthedocs.io ?

**Comment by DerThorsten** [comment]
> Shouldn't this issue be more about having a nice documentation on ReadTheDocs, like https://xeus-python-kernel.readthedocs.io ?

At some point we should have a readthedocs documentation. But with this issue I just ment *some  minimal* documentation st. other people can start to play around with it.
I will add another issue for the rtd build.   Btw the prefix.dev team moved all their documentation from readthedocs to mkdocs  on github pages.

**Comment by DerThorsten** [comment]
https://github.com/jupyterlite/xeus/issues/17

**Comment by jtpio** [comment]
Right. mkdocs would be fine, although the sphinx / pydata-sphinx-theme is still commonly used across Jupyter repos, it could make sense to stick to it for the time being (and maybe suggest mkdocs as an alternative for the future?)

In terms of work, copy pasting https://github.com/jupyterlite/xeus-python-kernel/tree/main/docs here would likely do most of it.
