### ISSUE TITLE
Syntax highlights were gone in code cells for newly created notebooks 

### ISSUE THREAD

**Issue by MRYingLEE** [jupyterlite/xeus#86]
For both Xeus-Javascript and Xeus-Python kernel, in all newly created notebooks, syntax highlights were gone in code cells. While P5.js kernel has no such issue.

A description in detail can be found at: https://github.com/jupyter-xeus/xeus-javascript/issues/34.

Most likely there is a bug in Xeus.

Please check. 
Thanks,

**Comment by martinRenou** [comment]
Thanks for opening an issue. Is this still relevant? I cannot seem to reproduce:

![Screenshot from 2024-06-06 16-21-32](https://github.com/jupyterlite/xeus/assets/21197331/dc3dd2f7-6b39-4de7-808c-944b9b7d3bca)

**Comment by martinRenou** [comment]
Are you still able to reproduce this issue? I cannot seem to reproduce on https://jupyterlite-xeus.readthedocs.io/en/latest/lite/lab/index.html, syntax highlighting works

![Screenshot from 2024-06-06 16-23-50](https://github.com/jupyterlite/xeus/assets/21197331/e8b04f75-2e81-4f1e-9829-3f84f6ecc4ac)

**Comment by martinRenou** [comment]
Also tried with xeus-javascript which seems to work nicely on this deployment: https://jupyterlite-xeus--94.org.readthedocs.build/en/94/lite/lab/index.html

Would you be able to provide more information about your issue and how to reproduce it?

**Comment by MRYingLEE** [comment]
On the deployment of https://jupyterlite-xeus--94.org.readthedocs.build/en/94/lite/lab/index.html, both Python and Javascript kernel have not this issue anymore. BTW, on the latest version of https://jupyter-xeus.github.io/xeus-javascript/lab/index.html, the Javascript kernel has not this issue anymore too.

But I couldn't load https://jupyterlite-xeus.readthedocs.io/en/latest/lite/lab/index.html in both Edge and Chrome. A new issue happened as the following:
![image](https://github.com/jupyterlite/xeus/assets/11193534/57ce83c3-2891-4f6d-abad-c9094c9622f9)


https://jupyterlite-xeus.readthedocs.io/en/latest/lite/config-utils.js?_=31485bd
index.html:1 The resource https://jupyterlite-xeus.readthedocs.io/en/latest/lite/build/lab/bundle.js?_=31485bd was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

**Comment by martinRenou** [comment]
This seems unrelated to the xeus kernel, would you be able to open an issue to the jupyterlite repository?

**Comment by martinRenou** [comment]
Closing as the original issue is not relevant anymore
